name: Continuous testing and deployment
on: [push, pull_request]
jobs:
  # test:
  #   name: Run tests
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Install goss and dgoss
  #       uses: e1himself/goss-installation-action@v1.0.1
  #       with:
  #         # Goss release version to install
  #         version: "v0.3.13"
  #     - name: Checkout code
  #       uses: actions/checkout@v2
  #     - name: Build the Docker image
  #       uses: docker/build-push-action@v2.0.1
  #       with:
  #         push: false
  #         tags: hyzual/koel:test
  #         platforms: linux/amd64
  #     - name: Run goss tests on the image
  #       run: dgoss run hyzual/koel:test
  deploy:
    name: Deploy to Docker Hub
    runs-on: ubuntu-latest
    # needs: [test]
    # if: github.ref == 'refs/heads/master'
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
        id: qemu
        with:
          platforms: linux/amd64,linux/arm64,linux/arm/v7
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}
      - name: Build and push the production image
        uses: docker/build-push-action@v2.0.1
        with:
          push: true
          tags: hyzual/koel:latest
          platforms: ${{ steps.qemu.outputs.platforms }}
